version: "3"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "4173:4173" # Map container port 4173 to host port 4173
        depends_on:
            - backend # Ensure backend service is running before the frontend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "3001:3001" # Map container port 3001 to host port 3001
        environment:
            - PORT=3001
            - OPENAI_API_KEY=api-key
